#53 Selectable
eManPrague/frui.ts pull request #54
Opened 2021-10-13 19:08 UTC by kopecmi8

2021-10-14 09:42 UTC, gius requested changes

2021-10-14 09:42 UTC, gius commented on packages/datascreens/src/selectableList.ts
> +      selectedItems: IObservableArray<TEntity> = observable([]);
Can we use `Set` here?

2021-12-23 11:32 UTC, kopecmi8 commented on packages/datascreens/src/selectableList.ts
> +      selectedItems: IObservableArray<TEntity> = observable([]);
for sure

2022-01-03 13:11 UTC, gius commented on packages/datascreens/src/selectableList.ts
> +          this.selectedItems = observable(new Set([...this.items]));
If we recreate the observable set, wouldn't it break existing observers? 
Could we reuse the existing instance of the set?

You might want to check https://gitlab.eman.cz/pudplus/pud-frontend/-/blob/master/src/models/dataList.ts for inspiration.

2022-06-29 12:02 UTC, gius commented
Obsolete, solved in v1

2022-06-29 12:02 UTC, closed without merging